### ISSUE TITLE
Spin Contamination Appearance after Truncating Wavefunction

### ISSUE THREAD

**Issue by tbhuber** [QuantumPackage/qp2#126] opened 2020-08-17 15:30 UTC
I am using CIPSI for all-electron energy calculations. 

When I build a wavefunction for a CH3 radical with a 'fixed' number of determinants, I obtain an S^2 value of 0.75. I expected this value, since I am forcing the wavefunction to be an eigenfunction of S^2. But once I truncate my wavefunction, the S^2 value becomes 1.00 (qp_run truncate_wf_spin based on ci_threshhold). I observe the same results for a plethora of wavefunctions with different quantity of determinants and different molecules. See below for example of fci output and pt2 output respectively.

Please correct me if I am wrong, but there shouldn't be any triplet (or higher) states during the truncating step since there were none generated in the previous step of building the wave function. Is it possible that the S^2 value is being miscalculated during the pt2 calculation?

N_det             =      4626334
 N_states          =            1
 N_sop             =       311088
 
 * State            1
 < S^2 >         =   0.75000002079000971     
 E               =   -39.811606632198909     
 Variance        =    7.1084719944476002E-002
 PT norm         =    1.4633135370513599E-002
 PT2             =   -2.7270756336503156E-003
 rPT2            =   -2.7264918136369214E-003
 E+PT2            =   -39.814333707832560       +/-    5.4679372548341915E-006
 E+rPT2           =   -39.814333124012549       +/-    5.4667666634644601E-006

 N_det             =      1855164
 N_states          =            1
 N_sop             =       263186

 * State            1
 < S^2 >         =    1.0000241195616941
 E               =   -39.811260478586149
 Variance        =    9.6033003388409588E-002
 PT norm         =    1.5253829569668725E-002
 PT2             =   -3.2844583094855159E-003
 rPT2            =   -3.2836942617489638E-003
 E+PT2            =   -39.814544936895636       +/-    6.4219870258990843E-006
 E+rPT2           =   -39.814544172847896       +/-    6.4204931099504075E-006

**Comment by kgasperich** [comment] 2020-08-20 20:55
Thanks for pointing this out, we'll look into it
@anbenali 
@TApplencourt

**Comment by kgasperich** [comment] 2020-08-20 21:02
@tbhuber do you have a small example so we can be sure we're reproducing the same issue?
thanks!

**Comment by kgasperich** [comment] 2020-08-20 21:33
Here is a small example that shows this.
The <S^2> in the fci and pt2 output don't match.
[pt2-s2-issue.tar.gz](https://github.com/QuantumPackage/qp2/files/5105583/pt2-s2-issue.tar.gz)

**Comment by eginer** [comment] 2020-08-20 23:28
By truncating the wave function you clearly destroy the eigenfunction of S2
because you throw away a lot of "small" determinants which are useless for
the energy but very important for S2.

But I guess that if you would reminimize the energy within the truncated
set of determinants, without the constraint of being an eigenfunction of
S2, you will obtain something much closer to 0.75 .

So as a test, once that you have truncated the wave function, you can unset
the eigenfunction of S2 (check the keywords only_expected_s2 in davidson
and s2_eig in determinants, set them to false). Then, just run the
executable diagonalize_h and it will minimize the energy by optimizing the
CI coefficients.
Then, I expecy that the value of S2 will be closer to 0.75.
If it is not the case, then set to True the keuwords I mentioned above, but
the Davidson might not converge.
Best,
Manu

Le jeu. 20 août 2020 à 23:33, Kevin Gasperich <notifications@github.com> a
écrit :

**Comment by kgasperich** [comment] 2020-08-20 23:37
We have identified the issue, and it should be fixed soon.
It looks like it's just a problem with what's being printed, so your wavefunction and energy are all still correct.

When `pt2` is called, it builds `psi_s2` from [the provider](https://github.com/QuantumPackage/qp2/blob/253ec57ae0118fba44a3a31fca2ade621d0296a5/src/davidson/u0_h_u0.irp.f#L1-L15), and this sets it to <S^2> - S_z*(S_z-1) (or <S_+ S_->  in terms of ladder operators).

When `fci` is called, it sets [`psi_s2` equal to `CI_S2`](https://github.com/QuantumPackage/qp2/blob/253ec57ae0118fba44a3a31fca2ade621d0296a5/src/davidson/diagonalize_ci.irp.f#L223), and this is shifted by S_z*(S_z-1)
The shift is applied [here](https://github.com/QuantumPackage/qp2/blob/253ec57ae0118fba44a3a31fca2ade621d0296a5/src/determinants/s2.irp.f#L128) for full diagonalization, and [here](https://github.com/QuantumPackage/qp2/blob/253ec57ae0118fba44a3a31fca2ade621d0296a5/src/davidson/diagonalization_hs2_dressed.irp.f#L499) for the davidson.

So the `<S^2>` in the `fci` output is actually <S^2>, and the value from the `pt2` output is <S^2> - S_z*(S_z-1).

**Comment by kgasperich** [comment] 2020-08-20 23:45
for the high-spin cases (i.e. max Sz for that multiplicity), you should see:
```
fci   pt2
0.75  1
2     2
3.75  3
6     4
8.75  5
```

**Comment by tbhuber** [comment] 2020-08-21 05:11
Thank you gentlemen. I appreciate the time and effort you have invested in resolving the issue.

**Comment by TApplencourt** [comment] 2020-08-27 21:49
It's should be fixed after merging #127. 
Can you try to `git pull` and see if it fixed your problem @tbhuber ?
Thanks!

**Comment by tbhuber** [comment] 2020-09-01 17:28
@TApplencourt Unfortunately, I have qp2 installed on a cluster owned by a university and do not have privilege to git pull. They do not support using head versions, but I am currently seeking a work-a-round.

**Comment by kgasperich** [comment] 2020-09-01 17:48
you could try `wget https://github.com/QuantumPackage/qp2/archive/dev.zip`

**Closed** 2020-10-16 12:04 UTC
